// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model2_ASP_NET_EF_CodeFirst.Models;

#nullable disable

namespace Model2_ASP_NET_EF_CodeFirst.Migrations
{
    [DbContext(typeof(PRN222DbContext))]
    [Migration("20250214041155_InitialCreateV1")]
    partial class InitialCreateV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Model2_ASP_NET_EF_CodeFirst.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("8eaef07c-c429-47ff-91fa-9b76f895a38b"),
                            CategoryName = "Electronics",
                            Description = ""
                        },
                        new
                        {
                            CategoryId = new Guid("1d0fe75e-a229-4b64-80c1-25210269c0ef"),
                            CategoryName = "Clothing",
                            Description = ""
                        },
                        new
                        {
                            CategoryId = new Guid("dc087650-7558-48a9-a006-ac5cc2e6593f"),
                            CategoryName = "Home & Kitchen",
                            Description = ""
                        });
                });

            modelBuilder.Entity("Model2_ASP_NET_EF_CodeFirst.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("c363bd54-0da6-4c29-86c1-ac9b8a0f0361"),
                            CategoryId = new Guid("8eaef07c-c429-47ff-91fa-9b76f895a38b"),
                            Price = 1000,
                            ProductName = "Laptop"
                        },
                        new
                        {
                            ProductId = new Guid("733726a6-8cec-44c5-8123-a1c913a6ac39"),
                            CategoryId = new Guid("1d0fe75e-a229-4b64-80c1-25210269c0ef"),
                            Price = 20,
                            ProductName = "T-Shirt"
                        },
                        new
                        {
                            ProductId = new Guid("e3a35504-1e53-4106-bfb5-9633f342e4e2"),
                            CategoryId = new Guid("dc087650-7558-48a9-a006-ac5cc2e6593f"),
                            Price = 50,
                            ProductName = "Blender"
                        });
                });

            modelBuilder.Entity("Model2_ASP_NET_EF_CodeFirst.Models.Product", b =>
                {
                    b.HasOne("Model2_ASP_NET_EF_CodeFirst.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Model2_ASP_NET_EF_CodeFirst.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
