// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model2_ASP_NET_EF_CodeFirst.Models;

#nullable disable

namespace Model2_ASP_NET_EF_CodeFirst.Migrations
{
    [DbContext(typeof(PRN222DbContext))]
    partial class PRN222DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Model2_ASP_NET_EF_CodeFirst.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("cec14050-ae21-4f85-8488-744be8ad57fc"),
                            CategoryName = "Electronics",
                            Description = ""
                        },
                        new
                        {
                            CategoryId = new Guid("8277c5d7-f4e3-4b42-b7c0-0ba29d42cf01"),
                            CategoryName = "Clothing",
                            Description = ""
                        },
                        new
                        {
                            CategoryId = new Guid("a2a03748-c64d-472d-895d-be0d97486e4b"),
                            CategoryName = "Home & Kitchen",
                            Description = ""
                        });
                });

            modelBuilder.Entity("Model2_ASP_NET_EF_CodeFirst.Models.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShipAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Model2_ASP_NET_EF_CodeFirst.Models.OrderDetails", b =>
                {
                    b.Property<Guid>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Discount")
                        .HasColumnType("float");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Model2_ASP_NET_EF_CodeFirst.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("9795f5f0-64d3-4cc7-ac11-28eac50f5e6f"),
                            CategoryId = new Guid("cec14050-ae21-4f85-8488-744be8ad57fc"),
                            Price = 1000,
                            ProductName = "Laptop"
                        },
                        new
                        {
                            ProductId = new Guid("52814b42-95e3-45bf-b95c-cc4e47d33561"),
                            CategoryId = new Guid("8277c5d7-f4e3-4b42-b7c0-0ba29d42cf01"),
                            Price = 20,
                            ProductName = "T-Shirt"
                        },
                        new
                        {
                            ProductId = new Guid("b280c07d-6060-4358-971b-631badddd906"),
                            CategoryId = new Guid("a2a03748-c64d-472d-895d-be0d97486e4b"),
                            Price = 50,
                            ProductName = "Blender"
                        });
                });

            modelBuilder.Entity("Model2_ASP_NET_EF_CodeFirst.Models.OrderDetails", b =>
                {
                    b.HasOne("Model2_ASP_NET_EF_CodeFirst.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model2_ASP_NET_EF_CodeFirst.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Model2_ASP_NET_EF_CodeFirst.Models.Product", b =>
                {
                    b.HasOne("Model2_ASP_NET_EF_CodeFirst.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Model2_ASP_NET_EF_CodeFirst.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Model2_ASP_NET_EF_CodeFirst.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
