// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Module2_ASP_NET_MVC_EF_CodeFirst.Models;

#nullable disable

namespace Module2_ASP_NET_MVC_EF_CodeFirst.Migrations
{
    [DbContext(typeof(PRN222DBContext))]
    [Migration("20250217094715_InitData")]
    partial class InitData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Module2_ASP_NET_MVC_EF_CodeFirst.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("63ade4c0-9740-4ea8-a3d5-d22d892b38f1"),
                            CategoryName = "Điện thoại",
                            Description = "Các sản phẩm điện thoại di động"
                        },
                        new
                        {
                            CategoryId = new Guid("603dc73b-20cc-4b65-86cb-ba7e73955b69"),
                            CategoryName = "Laptop",
                            Description = "Các sản phẩm laptop cao cấp"
                        });
                });

            modelBuilder.Entity("Module2_ASP_NET_MVC_EF_CodeFirst.Models.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShipAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Module2_ASP_NET_MVC_EF_CodeFirst.Models.OrderDetail", b =>
                {
                    b.Property<Guid>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Discount")
                        .HasColumnType("float");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Module2_ASP_NET_MVC_EF_CodeFirst.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("e3fef37c-8b0d-4ac9-b984-262a7d92c825"),
                            CategoryId = new Guid("63ade4c0-9740-4ea8-a3d5-d22d892b38f1"),
                            Price = 25000000,
                            ProductName = "IPhone 16 Pro"
                        },
                        new
                        {
                            ProductId = new Guid("b1ff595c-adf6-4534-9db4-c77e2a3aac2d"),
                            CategoryId = new Guid("63ade4c0-9740-4ea8-a3d5-d22d892b38f1"),
                            Price = 24000000,
                            ProductName = "Samsung Galaxy S25 Ultra"
                        },
                        new
                        {
                            ProductId = new Guid("dde5e481-d93b-412e-96a0-981f438ad338"),
                            CategoryId = new Guid("603dc73b-20cc-4b65-86cb-ba7e73955b69"),
                            Price = 65000000,
                            ProductName = "Macbook Pro M4"
                        });
                });

            modelBuilder.Entity("Module2_ASP_NET_MVC_EF_CodeFirst.Models.OrderDetail", b =>
                {
                    b.HasOne("Module2_ASP_NET_MVC_EF_CodeFirst.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module2_ASP_NET_MVC_EF_CodeFirst.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Module2_ASP_NET_MVC_EF_CodeFirst.Models.Product", b =>
                {
                    b.HasOne("Module2_ASP_NET_MVC_EF_CodeFirst.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Module2_ASP_NET_MVC_EF_CodeFirst.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Module2_ASP_NET_MVC_EF_CodeFirst.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
